version: '3.8'

services:
  app:
    build: .
    container_name: kanbanjs-front
    restart: always
    env_file: ./.env
    
    ports:
      - 3000:3000

    volumes:
      - .:/usr/app
    stdin_open: true
    tty: true